### ISSUE TITLE
Implement API so that it matches the one from the wikidatacomplete plugin

### ISSUE THREAD

**Issue by D063520** [WikidataComplete/wikidatacomplete-backend#11]
- copy it from the online version
- implement it in the backend
- test locally if it works by poining the wikidata plugin (installed on your wikidata account!) to your local server and check if it is working

**Comment by lalit97** [comment]
- covered the random API

**Comment by lalit97** [comment]
wrote new APIs for accepting and rejecting a fact also 
PR #16 
tested locally with postman and wikidata plugin. 
All tasks done for this issue can be closed.
