### ISSUE TITLE
Implement Webservice interface for fetching the fact candidate of a Wikidata entity 

### ISSUE THREAD

**Issue by anbo-de** [WikidataComplete/wikidatacomplete-backend#13]
As a developer, I want to see existing facts.

- [x] As a dev, I want to see fact candidates from the new service retrieved via RESTful call for a specific Wikidata entity (e.g., `GET /facts/Q1106`)

**Comment by lalit97** [comment]
PR: https://github.com/WikidataComplete/wikidatacomplete-backend/pull/14

1. Current API  
![Screenshot from 2022-07-04 17-51-39](https://user-images.githubusercontent.com/31045288/177153898-52bc417b-9b29-448a-9241-d1e17c07e053.png)

2. New API 
![Screenshot from 2022-07-04 17-51-50](https://user-images.githubusercontent.com/31045288/177153980-fed040f1-53e6-4513-a1e7-def643b60969.png)

**Comment by Perevalov** [comment]
@anbo-de We checked it, looks good. Please, review and close the issue if everything is ok

**Comment by lalit97** [comment]
closed with #14 and #20
