### ISSUE TITLE
fix css of wikidata complete plugin

### ISSUE THREAD

**Issue by D063520** [WikidataComplete/wikidatacomplete-backend#2]

**Comment by lalit97** [comment]
I have made changes in CSS, deployed and tested for https://www.wikidata.org/wiki/Q10889416

earlier
![Screenshot from 2022-06-15 11-01-09](https://user-images.githubusercontent.com/31045288/173839669-da7412fc-6a7d-49ff-9048-b21f19609b2a.png)

now 
![Screenshot from 2022-06-15 18-46-29](https://user-images.githubusercontent.com/31045288/173839692-c1a81ce8-361a-4906-b20f-3c87500d9d01.png)

**Comment by D063520** [comment]
Looks good! Maybe you can just reduce the spacing between the boxes (the big ones, each one containing a statement)

**Comment by lalit97** [comment]
Thanks :) I have reduced the spacing between the boxes. Now it is in sync with already present statement boxes.


![Screenshot from 2022-06-16 00-11-08](https://user-images.githubusercontent.com/31045288/173901945-bcc97643-692f-4af2-a8fc-8d1fd5043c9c.png)
(screenshot is taken from https://www.wikidata.org/wiki/Q10889416)

**Comment by D063520** [comment]
nice!
