### ISSUE TITLE
Log in functionality via Wikidata

### ISSUE THREAD

**Issue by Perevalov** [WikidataComplete/wikidatacomplete-backend#45]
As a user of a WikidataComplete Web UI, I want to log in using my Wikimedia account.

Remark: An OAuth2 mechanism would be preferred.

**Comment by anbo-de** [comment]
@lalit97 I suggest you ask in the Wikimedia chat/forum about how to do such an login mechanism.

**Comment by lalit97** [comment]
Thanks for the suggestion @anbo-de will reach out to the community :)

**Comment by lalit97** [comment]
meeting notes: we need to implement Oauth via Wikidata instead of MediaWiki

**Comment by lalit97** [comment]
This is now deployed on prod. Can be tested by visting https://datacompletewiki.toolforge.org/accounts/login for now.
Closing with #58
